### 用户登录和注册. （基于密码）
POST {{prefix}}/session
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "{{account}}",
  "password": "{{password}}"
}


### 用户登录和注册. （基于统一认证系统的 Cookie）
POST {{prefix}}/session
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "account": "{{account}}",
  "cookie": "{{cookie}}"
}

